

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=Cheese100!
      - RAILS_ENV=development
      - CORS_ORIGINS=http://localhost:8080  # Update this with your Flutter web port if needed
    depends_on:
      - neo4j
    volumes:
      - .:/workspace
    networks:
      - app-network

  neo4j:
    image: neo4j:5.11
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/Cheese100!
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  app-network:
    driver: bridge